In [1]:
import pandas as pd
import numpy as np
from pandas.io.json import json_normalize
import matplotlib.pyplot as plt
import requests
import time
import datetime
import pymysql
import pymysql.cursors
from sqlalchemy import create_engine

import warnings
warnings.filterwarnings(action='ignore')

In [2]:
url = 'https://kr.api.riotgames.com/'
api_key = 'RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df'
api = '?api_key='+api_key

In [3]:
host = '127.0.0.1'
port = '3306'
sid = 'League Of Legends'

user = 'root'
password = 'tmddk720'

## Upload to Database

In [4]:
def upload_df_to_db(host, port, sid, user, password, table, df, if_exists='append'):
    
    connection = pymysql.connect(host=host,
                                user=user,
                                password=password,
                                db=sid,
                                charset='utf8',
                                cursorclass=pymysql.cursors.DictCursor)

    engine = create_engine("mysql+pymysql://{user}:{password}@{host}/{db}"
                        .format(user=user, password=password, host=host, db=sid))


    try:
        with connection.cursor() as cursor:
#             print('upload')
            df.to_sql(name=table, con=engine, if_exists=if_exists, index=False)
            connection.commit()
#             print('upload db')
    
    except Exception as e:
        print(e)
                
    finally:
        connection.close()

In [5]:
def update_db(host, port, sid, user, password, sql, values, option='one'):
    
    connection = pymysql.connect(host=host,
                                user=user,
                                password=password,
                                db=sid,
                                charset='utf8',
                                cursorclass=pymysql.cursors.DictCursor)

    try:
        with connection.cursor() as cursor:
#             print('update')
            if option == 'one':
                cursor.execute(sql, values)
            elif option == 'many':
                cursor.executemany(sql, values)
                
            connection.commit()
#             print('update db')
    
    except Exception as e:
        print(e)
                
    finally:
        connection.close()

## get data from DB

In [6]:
def get_league_queue_from_db(tier):
    host = '127.0.0.1'
    port = '3306'
    sid = 'League Of Legends'

    user = 'root'
    password = 'tmddk720'
    
    con = pymysql.connect(host=host, user=user, password=password, db=sid, charset='utf8')
    
    try:
        league_queue_db = pd.read_sql("SELECT * FROM league_queue where tier = '" + tier + "'", con=con)
    except Exception as e:
        print(e)
    finally:
        con.close()
        
    return league_queue_db

In [7]:
def get_summoner_from_db(summonerId):
    host = '127.0.0.1'
    port = '3306'
    sid = 'League Of Legends'

    user = 'root'
    password = 'tmddk720'
    
    con = pymysql.connect(host=host, user=user, password=password, db=sid, charset='utf8')
    
    try:
        summoner_db = pd.read_sql("SELECT * FROM summoners where summonerId = '" + summonerId + "'", con=con)
    except Exception as e:
        print(e)
    finally:
        con.close()
        
    return summoner_db

In [8]:
def get_recent_gameId_from_db(summonerId):

    host = '127.0.0.1'
    port = '3306'
    sid = 'League Of Legends'

    user = 'root'
    password = 'tmddk720'
    
    con = pymysql.connect(host=host, user=user, password=password, db=sid, charset='utf8')
    sql = """SELECT gameId FROM `League Of Legends`.matchlists t1 
                WHERE t1.timestamp = (SELECT t2.timestamp FROM `League Of Legends`.matchlists t2 
                                        WHERE t2.summonerId = '%s' 
                                        ORDER BY t2.timestamp DESC LIMIT 1);""" %(summonerId)
    try:
        with con.cursor() as cursor:
            cursor.execute(sql)
            fetch = cursor.fetchall()
            
            if len(fetch) == 0:
                gameId = np.nan
            else:
                gameId = int(fetch[0][0])
    except Exception as e:
        print(e)
    finally:
        con.close()
    
    return gameId

In [9]:
#queue=420 : 소환사의 협곡
def get_gameId_list_from_db(queue='420', tier='CHALLENGER'):
    
    host = '127.0.0.1'
    port = '3306'
    sid = 'League Of Legends'

    user = 'root'
    password = 'tmddk720'
    
    con = pymysql.connect(host=host, user=user, password=password, db=sid, charset='utf8')
    sql = """SELECT gameId FROM matchlists JOIN league_queue ON matchlists.summonerId = league_queue.summonerId
                WHERE queue = %s AND tier = '%s' ORDER BY timestamp DESC;""" %(queue, tier)

    try:
        with con.cursor() as cursor:
            cursor.execute(sql)
            fetch = cursor.fetchall()
            
            if len(fetch) == 0:
                gameId_list = np.nan
            else:
                gameId_list = [int(x[0]) for x in fetch]
                
    except Exception as e:
        print(e)
    finally:
        con.close()
    
    return gameId_list

## 티어별 소환사 리스트 저장

In [45]:
#challenger to master
ch_queue_req = requests.get(url + 'lol/league/v4/challengerleagues/by-queue/RANKED_SOLO_5x5'+api)
gm_queue_req = requests.get(url + 'lol/league/v4/grandmasterleagues/by-queue/RANKED_SOLO_5x5'+api)
ms_queue_req = requests.get(url + 'lol/league/v4/masterleagues/by-queue/RANKED_SOLO_5x5'+api)

challengers = json_normalize(ch_queue_req.json()['entries'])
challengers['tier'] = 'CHALLENGER'
challengers['update'] = datetime.datetime.now()

grandmasters = json_normalize(gm_queue_req.json()['entries'])
grandmasters['tier'] = 'GRANDMASTER'
grandmasters['update'] = datetime.datetime.now()

masters = json_normalize(ms_queue_req.json()['entries'])
masters['tier'] = 'MASTER'
masters['update'] = datetime.datetime.now()

In [46]:
ch_to_dia = pd.concat([challengers, grandmasters, masters], ignore_index=True)

In [47]:
#diamondI to diamondIV
dias = {}

for tier in ['I', 'II', 'III', 'IV']:
    print('==================', tier, '==================')
    dias[tier] = pd.DataFrame()
    
    page = 1
    
    while(True):
        dia_queue_req = requests.get(url + 'lol/league/v4/entries/RANKED_SOLO_5x5/DIAMOND/'+tier +
                                     '?page=' + str(page) + '&api_key='+api_key)
        
        #2분에 100개 요청 넘어가는 경우
        if dia_queue_req.status_code == 429:
            time.sleep(120)
            continue
            
        #더이상 데이터 페이지가 없는 경우
        if len(dia_queue_req.content) == 2:
            print(tier, page)
            break
        else:
            temp_dias = json_normalize(dia_queue_req.json())
            temp_dias['update'] = datetime.datetime.now()
            dias[tier] = dias[tier].append(temp_dias)
            page += 1
    
    ch_to_dia = pd.concat([ch_to_dia, dias[tier]], ignore_index=True)
    
print('# of summoners:    ', len(ch_to_dia))
print('# of challengers:  ', len(challengers))
print('# of grandmasters: ', len(grandmasters))
print('# of masters:      ', len(masters))
print('# of diamond1:     ', len(dias['I']))
print('# of diamond2:     ', len(dias['II']))
print('# of diamond3:     ', len(dias['III']))
print('# of diamond4:     ', len(dias['IV']))
print()

ch_to_dia.tail()

================== I ==================
I 37
================== II ==================
II 64
================== III ==================
III 130
================== IV ==================
IV 374
# of summoners:     125452
# of challengers:   300
# of grandmasters:  700
# of masters:       1652
# of diamond1:      7331
# of diamond2:      12813
# of diamond3:      26274
# of diamond4:      76382

,summonerId,summonerName,leaguePoints,rank,wins,losses,veteran,inactive,freshBlood,hotStreak,tier,update,leagueId,queueType,miniSeries.target,miniSeries.wins,miniSeries.losses,miniSeries.progress
125447,LOo4qRdO2I17eF6k2xv-IMh0uz1KF9JplQuJ9kxxCef4yrY,찡찡루삥뽕,100,IV,133,77,False,False,False,True,DIAMOND,2020-09-10 15:47:45.722671,5e640a31-082b-483f-b7ff-8e5206d30c81,RANKED_SOLO_5x5,2.0,0.0,0.0,NNN
125448,o7iA9EOqqHTKTRJter2kt64GMtzeyHzVvpsPpg1m5cmu3Sg,YxxxxxxxxyC,0,IV,106,76,False,False,False,False,DIAMOND,2020-09-10 15:47:45.722671,c127b080-4359-462b-91f0-6070f3b6442d,RANKED_SOLO_5x5,NaN,NaN,NaN,NaN
125449,Ddt8nRrIq1pSWLB_JhDdTPNzq8MiB5tOAZ3f1F3rnFlb8w,buff markersman,3,IV,132,115,False,False,False,False,DIAMOND,2020-09-10 15:47:45.722671,c6b80a17-e510-48a0-83dd-2fdbbb8ef45d,RANKED_SOLO_5x5,NaN,NaN,NaN,NaN
125450,JUlvU2yNiOSbkj_aattbfvFR817IhDeOhH5thPsi6NkRZk4,zao zi ge ge,9,IV,172,142,False,False,False,False,DIAMOND,2020-09-10 15:47:45.722671,bf409f7f-2fe6-4f1a-8ef2-bc70d3996fcc,RANKED_SOLO_5x5,NaN,NaN,NaN,NaN
125451,7hkWQ8mn89PKScd-P7aUeTiP4NaNNaCkAFGc4oL09nZkygc,예술적인 솔킬각,88,IV,332,282,True,False,False,True,DIAMOND,2020-09-10 15:47:45.722671,fffc1cf1-8c91-4f0a-ba64-a646e9266cb8,RANKED_SOLO_5x5,NaN,NaN,NaN,NaN

In [10]:
ch_to_dia.to_csv('./data/ch_to_dia.csv')

In [63]:
#Timestamp to datetime
ch_to_dia['update'] = ch_to_dia['update'].apply(lambda x: x.to_pydatetime().strftime("%Y-%m-%d %H:%M:%S"))

sql = """INSERT INTO `League Of Legends`.league_queue 
            (summonerId, summonerName, tier, leaguePoints, `rank`, wins, losses, `update`) 
         VALUES (%s, %s, %s, %s, %s, %s, %s, %s)  
         ON DUPLICATE KEY UPDATE \
            summonerName = VALUES(summonerName), \
            tier = VALUES(tier), \
            leaguePoints = VALUES(leaguePoints), \
            `rank` = VALUES(`rank`), \
            wins = VALUES(wins), \
            losses = VALUES(losses), \
            `update` = VALUES(`update`);"""

league_queue_columns = ['summonerId', 'summonerName', 'tier', 'leaguePoints', 'rank', 'wins', 'losses', 'update']
values = list(ch_to_dia[league_queue_columns].itertuples(index=False, name=None))

update_db(host, port, sid, user, password, sql, values, option='many')

## 티어별 소환사 데이터 저장

In [ ]:
for tier in ['CHALLENGER', 'GRANDMASTER', 'MASTER']:
    
    print('==================', tier, '==================')
    league_queue_df = get_league_queue_from_db(tier)
    
    N = len(league_queue_df)
    i = 0
    
    while(i<N):
        si = league_queue_df.summonerId.values[i]
        
        try:
            summoner_req = requests.get(url + 'lol/summoner/v4/summoners/' + si + api)
            summoner_df = json_normalize(summoner_req.json())
            print('{0}   {1:5d}: {2}'.format(datetime.datetime.now().strftime("%H:%M:%S"), i, summoner_df.name[0]))
            
            summonerName = summoner_df['name'][0]
            summonerId = summoner_df['id'][0]
            accountId = summoner_df['accountId'][0]
            puuid = summoner_df['puuid'][0]
            summonerLevel = str(summoner_df['summonerLevel'][0])
            profileIconId = str(summoner_df['profileIconId'][0])
            revisionDate = str(summoner_df['revisionDate'][0])
            update = datetime.datetime.now()

            sql = """INSERT INTO `League Of Legends`.summoners 
                        (summonerName, summonerId, accountId, puuid, summonerLevel, profileIconId, revisionDate, `update`) 
                     VALUES (%s, %s, %s, %s, %s, %s, %s, %s)  
                     ON DUPLICATE KEY UPDATE \
                        summonerName = VALUES(summonerName), \
                        accountId = VALUES(accountId), \
                        puuid = VALUES(puuid), \
                        summonerLevel = VALUES(summonerLevel), \
                        profileIconId = VALUES(profileIconId), \
                        revisionDate = VALUES(revisionDate), \
                        `update` = VALUES(`update`);"""

            values = (summonerName, summonerId, accountId, puuid, summonerLevel, profileIconId, revisionDate, update)

            update_db(host, port, sid, user, password, sql, values)
        
        
        except Exception as e:
            #2분에 100개 제한
            if summoner_req.status_code == 429:
                time.sleep(120)
                continue
            
            #없는 데이터
            if summoner_req.status_code == 404:
                print('{0}   {1} '.format(datetime.datetime.now().strftime("%H:%M:%S"), e))
                pass
            else:
                print('{0}   {1} '.format(datetime.datetime.now().strftime("%H:%M:%S"), e))
                time.sleep(5)
                continue

        i += 1
        break
    break

## 소환사별 매치 리스트 다운로드

In [ ]:
for tier in ['CHALLENGER', 'GRANDMASTER', 'MASTER']:
    
    print('==================', tier, '==================')
    league_queue_df = get_league_queue_from_db(tier)
    
    N = len(league_queue_df)
    i = 0
    
#     passthrough = True
    
    #for summoner
    while(i<N):
        
        #tier별 소환사 목록에서 summonerId, summonerName 얻기
        si = league_queue_df.summonerId.values[i]
        sn = league_queue_df.summonerName.values[i]
        
#         if(sn == '대륜명왕'):
#             passthrough = False
        
#         if(passthrough):
#             i += 1
#             continue
        
        #summonerId로 summoner 데이터 불러오기
        summoner_df = get_summoner_from_db(si)
        if len(summoner_df) == 0:
            i += 1
            continue
            
        ai = summoner_df['accountId'][0]
        
        #summonerId로 db에 저장되어 있는 가장 최근 매치 데이터 불러오기
        recent_gameId = get_recent_gameId_from_db(si)
        
        #begin index
        bi = 0
        #이미 저장된 매치까지 다시 검색하는 건 아닌지 검사
        yn_search = True
        
        while(yn_search):
            
            try:
                matches_req = requests.get(url + 'lol/match/v4/matchlists/by-account/' + ai + api + '&season=13&beginIndex=' + str(bi*100))           

                #2분에 100개 요청 넘어가는 경우
                if matches_req.status_code == 429:
                    time.sleep(120)
                    continue

                #더이상 데이터 페이지가 없는 경우
                if len(matches_req.json()['matches']) == 0:
                    print(sn, bi)
                    break
                
                #데이터 페이지를 불러온 경우
                else:
                    matches_df = json_normalize(matches_req.json())
                    matches_df = json_normalize(matches_df['matches'][0]).drop(columns=['role', 'lane'])
                    
                    matches_df['summonerName'] = sn
                    matches_df['summonerId'] = si
                    matches_df['accountId'] = ai
                    matches_df['timestamp'] = matches_df['timestamp'].apply(lambda x: datetime.datetime.fromtimestamp(x/1000).strftime("%Y-%m-%d %H:%M:%S"))
                    
                    sql = """INSERT INTO `League Of Legends`.matchlists
                                (platformId, gameId, champion, queue, season, timestamp, summonerName, summonerId, accountId) 
                             VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)  
                             ON DUPLICATE KEY UPDATE 
                                platformId = VALUES(platformId), 
                                champion = VALUES(champion), 
                                queue = VALUES(queue),
                                season = VALUES(season),
                                timestamp = VALUES(timestamp),
                                summonerName = VALUES(summonerName);"""
                    values = list(matches_df.itertuples(index=False, name=None))
                    
                    #db에 데이터 업데이트
                    update_db(host, port, sid, user, password, sql, values, option='many')
                    bi += 1
                    
                    #데이터베이스에 기록된 경기까지 찾은 경우 더 이상 검색하지 않음
                    if(recent_gameId in matches_df['gameId'].values):
                        print(sn, bi)
                        yn_search = False
                    
            except Exception as e:
                #없는 데이터
                if matches_req.status_code == 404 or matches_req.status_code == 400:
                    print('{0}   {1:10s} {2}'.format(datetime.datetime.now().strftime("%H:%M:%S"), sn, e))
                    break
                else:
                    print('{0}   {1:10s} {2}'.format(datetime.datetime.now().strftime("%H:%M:%S"), sn, e))
                    time.sleep(5)
                    continue
        
        i += 1

## 매치별 매치 데이터 다운

In [10]:
def cleanse_match_data(match_df):
    
    gameId = match_df['gameId'][0]
    
    teams_df = json_normalize(match_df['teams'][0])
    ptcp_df = json_normalize(match_df['participants'][0])
    ptcp_idt_df = json_normalize(match_df['participantIdentities'][0])
    
    
    #=====================================================================================================
    # teams_df 정리
    # - teamId, win, firstBlood, firstTower, firstInhibitor, firstBaron, firstDragon, firstRiftHerald,
    #   towerKills, inhibitorKills, baronKills, vilemawKills, riftHeraldKills, dominionVictoryScore, ban
    #=====================================================================================================
    
    #ban 목록 정리
    bans = {}
    for t in [0, 1]:
        teamId = (t+1)*100
        bans[str(teamId)] = json_normalize(teams_df['bans'][t]).T
        bans[str(teamId)].rename(columns={0:'ban1', 1:'ban2', 2:'ban3', 3:'ban4', 4:'ban5'}, inplace=True)
        bans[str(teamId)]['teamId'] = teamId
    bans = pd.concat([bans['100'], bans['200']])
    bans = bans.loc['championId']

    teams_df = pd.merge(teams_df.drop(columns=['bans']), bans, on='teamId', how='outer')
    teams_df['gameId'] = gameId
    for c in teams_df.columns:
        teams_df[c] = teams_df[c].astype(str)
    
    
    #=====================================================================================================
    # participants_df 정리
    # - participantId, teamId, championId, spell, win, item, kda, damage, gold, xp, visionScore, ward, rune
    #=====================================================================================================
   
    #participants column 명칭 정리
    ptcp_df.columns = ptcp_df.columns.str.strip().str.replace('stats.', '')
    ptcp_df.columns = ptcp_df.columns.str.strip().str.replace('timeline.', '')
    ptcp_df.columns = ptcp_df.columns.str.strip().str.replace('.', ':')
#     ptcp_df.columns = ptcp_df.columns.str.strip().str.replace('0-end', '0-10')
#     ptcp_df.columns = ptcp_df.columns.str.strip().str.replace('10-end', '10-20')
#     ptcp_df.columns = ptcp_df.columns.str.strip().str.replace('20-end', '20-30')
#     ptcp_df.columns = ptcp_df.columns.str.strip().str.replace('30-end', '30-40')
#     ptcp_df.columns = ptcp_df.columns.str.strip().str.replace('40-end', '40-50')
#     ptcp_df.columns = ptcp_df.columns.str.strip().str.replace('50-end', '50-60')
    
    #sq에 삽입하기 위해 특정 column 명칭 양쪽으로 ₩ 붙이기
    cc = ptcp_df.filter(regex='Deltas').columns
    ccc = ['`' + c + '`' for c in cc]
    ptcp_df.rename(columns=dict(zip(cc,ccc)), inplace=True)
    
    #중복 column 제거
    ptcp_df = ptcp_df.loc[:, ~ptcp_df.columns.duplicated()]
    
    #participants에서 제거할 column list
    participants_delete_list = ['killingSprees', 'doubleKills', 'tripleKills', 
                               'quadraKills', 'pentaKills', 'combatPlayerScore', 'objectivePlayerScore', 
                               'totalPlayerScore', 'totalScoreRank', 'role', 'lane']
    for i in range(10):
        participants_delete_list.append('playerScore'+str(i))
        
    #participants에서 필요 없는 column 제거
    ptcp_df = ptcp_df[ptcp_df.columns.drop(participants_delete_list)]
    ptcp_df = ptcp_df[ptcp_df.columns.drop(list(ptcp_df.filter(regex='Diff')))]
    ptcp_df = ptcp_df[ptcp_df.columns.drop(list(ptcp_df.filter(regex='Deltas')))]
    
    ptcp_df['gameId'] = gameId
    for c in ptcp_df.columns:
        ptcp_df[c] = ptcp_df[c].astype(str)
    
    
    #=====================================================================================================
    # participant_identities_df 정리
    # - participantId, accountId, summonerName, summonerId
    #=====================================================================================================
   
    #participant identities column 명칭 정리
    ptcp_idt_df.columns = ptcp_idt_df.columns.str.strip().str.replace('player.', '')
    
    #participant identities에서 필요 없는 column 제거
    ptcp_idt_df = ptcp_idt_df[ptcp_idt_df.columns.drop(['platformId', 'currentPlatformId', 'currentAccountId',
                                                        'matchHistoryUri', 'profileIcon'])]
  
    ptcp_idt_df['gameId'] = gameId
    for c in ptcp_idt_df.columns:
        ptcp_idt_df[c] = ptcp_idt_df[c].astype(str)
   
    
    #=====================================================================================================
    # match_df 정리
    # - gameId, platformId, gameCreation, gameDuration, queueId, mapId, seasonId, gameVersion, gameType
    #=====================================================================================================
   
    match_df = match_df.drop(columns=['teams', 'participants', 'participantIdentities'])
    match_df['gameCreation'] = match_df['gameCreation'].apply(lambda x: datetime.datetime.fromtimestamp(x/1000).strftime("%Y-%m-%d %H:%M:%S"))
    
    for c in match_df.columns:
        match_df[c] = match_df[c].astype(str)
   
    return match_df, teams_df, ptcp_df, ptcp_idt_df

In [11]:
gameId_list = get_gameId_list_from_db(queue='420', tier='CHALLENGER')
gameId_list = list(set(gameId_list))

In [12]:
gameId_list.index(4394328998)

156409

In [ ]:
i = 156409
N = len(gameId_list)
print(N)

while(i<N):    
    try:
        gameId = gameId_list[i]
        match_req = requests.get(url + 'lol/match/v4/matches/' + str(gameId) + api)           

        #2분에 100개 요청 넘어가는 경우
        if match_req.status_code == 429:
            time.sleep(120)
            continue
    
        match_df = json_normalize(match_req.json())
        match_df, teams_df, ptcp_df, ptcp_idt_df = cleanse_match_data(match_df)
           
        #match_df    
        sql = "INSERT INTO `League Of Legends`.`match` (" +  ', '.join(match_df.columns) + ") " + \
            "VALUES (" + ', '.join('%s' for i in match_df.columns) + ") ON DUPLICATE KEY UPDATE " + \
            ', '.join('{0}=VALUES({0})'.format(c) for c in match_df.drop(columns=['gameId']).columns) + ';'
        values = list(match_df.itertuples(index=False, name=None))[0]
        update_db(host, port, sid, user, password, sql, values)

        #teams_df
        sql = "INSERT INTO `League Of Legends`.`match_teams` (" +  ', '.join(teams_df.columns) + ") " + \
            "VALUES (" + ', '.join('%s' for i in teams_df.columns) + ") ON DUPLICATE KEY UPDATE " + \
            ', '.join('{0}=VALUES({0})'.format(c) for c in teams_df.drop(columns=['gameId', 'teamId']).columns) + ';'
        values = list(teams_df.itertuples(index=False, name=None))
        update_db(host, port, sid, user, password, sql, values, 'many')
        
        #ptcp_df
        sql = "INSERT INTO `League Of Legends`.`match_participants` (" +  ', '.join(ptcp_df.columns) + ") " + \
            "VALUES (" + ', '.join('%s' for i in ptcp_df.columns) + ") ON DUPLICATE KEY UPDATE " + \
            ', '.join('{0}=VALUES({0})'.format(c) for c in ptcp_df.drop(columns=['gameId', 'participantId']).columns) + ';'
        values = list(ptcp_df.itertuples(index=False, name=None))
        update_db(host, port, sid, user, password, sql, values, 'many')
    
        #ptcp_idt_df
        sql = "INSERT INTO `League Of Legends`.`match_participant_identities` (" +  ', '.join(ptcp_idt_df.columns) + ") " + \
            "VALUES (" + ', '.join('%s' for i in ptcp_idt_df.columns) + ") ON DUPLICATE KEY UPDATE " + \
            ', '.join('{0}=VALUES({0})'.format(c) for c in ptcp_idt_df.drop(columns=['gameId', 'participantId']).columns) + ';'
        values = list(ptcp_idt_df.itertuples(index=False, name=None))
        update_db(host, port, sid, user, password, sql, values, 'many')
    
        if i%100 == 0:
            print('{0}   {1:10d}'.format(datetime.datetime.now().strftime("%H:%M:%S"), gameId))
        i += 1
    
    except Exception as e:
        #없는 데이터
        if match_req.status_code == 404 or match_req.status_code == 400:
            print('{0}   {1:10d} {2}'.format(datetime.datetime.now().strftime("%H:%M:%S"), gameId, e))
            break
        else:
            print('{0}   {1:10d} {2}'.format(datetime.datetime.now().strftime("%H:%M:%S"), gameId, e))
            time.sleep(5)
            continue

302265
14:39:03   3640403010
14:42:01   3640403191
14:44:55   4050396556
14:47:46   4619773483
14:50:38   4586219216
14:53:30   3993773950
14:56:21   3918276647 'gameId'
14:56:28   4252772405 'gameId'
14:56:35   3835963448
14:59:29   3714853110
15:01:50   3754174767 'gameId'
15:02:10   4243335512 'gameId'
15:02:34   4136380821
15:05:27   3630443057
15:08:21   4267977431
15:11:14   3780389745
15:14:05   4497615904
15:17:03   4142148813
15:19:56   3991154047
15:22:50   3719048747
15:25:45   4478742268
15:28:22   3893112671 'gameId'
15:28:42   3536072595
15:31:30   3923521613
15:34:16   3592696051
15:36:26   3878433042 'gameId'
15:37:14   4609290668
15:40:01   4457771611
15:42:47   3795071747
15:45:39   3942921134
15:48:25   4508103741
15:51:10   3715904757
15:54:01   4099159455
15:56:52   3738449501
15:59:48   3729012475
16:02:43   3694409625
16:05:41   4408490064
16:08:40   3648796924
16:11:36   3721673139
16:13:55   3606854131 'gameId'
16:14:39   3784587888
16:17:34   4280040217
16:20:06   3700177792 'gameId'
16:20:35   3790879698
16:23:32   4197727356
16:26:30   4216077585
16:29:26   3581689256
16:32:13   4524883541
16:35:03   3758374647
16:37:11   4237573903 'gameId'
16:39:55   3626254225
16:42:52   3521921065
16:45:48   4077142228
16:48:45   3806609819
16:51:39   4494475843
16:54:32   4081861379
16:57:27   4014752670
17:00:22   4101784658
17:03:11   3913041155
17:06:00   4262741449
17:08:51   3603187325
17:09:06   4469311162 'gameId'
17:11:44   3580643118
17:14:33   3658762215
17:17:18   3681831060
17:20:14   3807136111
17:23:07   3623111243
17:25:59   3625732838
17:28:53   4582558614
17:31:39   3756280910
17:31:54   3700182151 'gameId'
17:34:32   3831778538
17:35:12   4115418501 'gameId'
17:37:29   3767291311
17:40:21   3564916315
17:43:09   3606859505
17:46:01   4252258198
17:48:52   3544469546
17:51:49   4330901747
17:54:41   4100739491
17:57:33   3527692890
18:00:20   4296299259
18:00:51   3532936026 'gameId'
18:03:20   4531180457
18:06:07   3721679947
18:08:53   3884733678
18:11:38   4077671848
18:11:53   3969144291 'gameId'
18:14:30   4048311880
18:17:15   3713135782 'gameId'
18:17:21   4513879783
18:20:08   3613677446
18:22:53   4327757895
18:25:42   3789838584
18:28:27   3976485294
18:31:11   4422130261
18:33:57   3556006645
18:36:44   3752090530
18:39:31   3856423979
18:39:32   4227095599 'gameId'
(1366, "Incorrect integer value: 'nan' for column 'perkSubStyle' at row 2")
18:42:22   4076625126
18:45:09   4506017147
18:47:55   3678166585
18:50:41   4161560300
18:53:30   4439433126
18:56:21   3722731617
18:56:34   4380188814 'gameId'
18:56:44   4156317853 'gameId'
18:59:21   4415316268
19:00:02   4249117150 'gameId'
19:02:13   3709100523
19:05:02   4001129108
19:07:50   3699663650
19:10:33   4510737344 'gameId'
19:10:42   4328809422
19:13:31   3577504907
19:16:16   4269040931
19:19:04   4159464910
19:21:49   3637798518
19:24:39   3522979612
19:27:25   4500776910
19:30:15   3591661676
(1366, "Incorrect integer value: 'nan' for column 'perkSubStyle' at row 4")
19:33:06   4399589681
19:33:18   4493961570 'gameId'
19:35:58   3658770910
19:38:48   4484000404
19:41:39   3617352502
19:44:30   3702287319
19:47:19   4256984183
19:50:09   4262751531
19:54:18   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
19:55:53   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
19:57:28   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
19:59:03   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:00:38   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:04:35   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:04:40   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:04:45   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:04:50   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:04:55   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:05:00   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:05:05   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:05:56   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:06:01   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:06:06   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:06:11   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:06:16   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:06:21   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:06:26   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:07:35   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:07:40   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:07:45   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:07:50   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:07:55   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
20:21:34   3515641298 HTTPSConnectionPool(host='kr.api.riotgames.com', port=443): Max retries exceeded with url: /lol/match/v4/matches/3515641298?api_key=RGAPI-972d84af-c217-4c04-9e93-21ed5d7986df (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd14e9c3190>: Failed to establish a new connection: [Errno 51] Network is unreachable'))
20:21:46   3597954532
20:24:34   4562644614
20:27:19   3658772318
20:30:04   4180439060
20:32:51   4362367187
20:33:14   3597955379 'gameId'
20:35:43   4496060805
20:38:28   4476138015
20:41:14   4579947185
20:44:01   4376523636
20:46:47   3584848956
20:49:35   3743184105
20:52:23   4270618012
20:55:12   3905713715
20:57:58   3669784284
20:58:27   3972822852 'gameId'
21:00:50   4359223159
21:03:43   4539054091
21:06:36   3583801507
21:09:28   4104419656
21:12:20   3597957637
21:15:13   3708582583
21:18:05   3951328088
21:21:04   4437867528
21:23:53   3816062115
21:26:43   4425809245
(1366, "Incorrect integer value: 'nan' for column 'perkSubStyle' at row 1")
21:29:31   4205084179
21:29:51   4491869794 'gameId'
21:32:22   4431576748
21:35:08   4080828253
21:37:56   4099178499
21:40:43   4431052985
21:43:33   3809771859
21:46:22   4197220883
21:49:11   3917775536
21:51:59   4288447324
21:52:09   3864822649 'gameId'
21:52:21   3604775828 'gameId'
21:55:00   3770450945
21:55:16   4115432529 'gameId'
21:57:57   4023157950
22:00:48   3914630500
22:03:38   3788277268
22:06:29   3532424889
22:09:18   4297885555
22:12:06   3959195680
22:14:57   3576989888
22:17:43   3847522651 'gameId'
22:17:57   3583281521
22:18:17   3644623263 'gameId'
22:21:00   4156328464
22:23:57   3664022183
22:26:54   3892611928
22:29:52   3958148082
22:32:49   4463561898
22:35:48   3715403108
22:38:46   4520185382
22:38:56   3594292796 'gameId'
22:41:45   4079259324
22:44:39   3880554316
22:47:34   4087123962
22:50:27   4269052077
22:50:28   3624177842 'gameId'
22:53:23   4056191332
22:53:38   4146368928 'gameId'
22:56:15   3780416014
22:59:02   3970208442
23:01:51   4454650723
23:04:38   4573139991
23:07:19   3709113492 'gameId'
23:07:35   3599537337
23:10:23   3852244335
23:13:08   4303132183
23:15:55   4266956476
23:16:26   3801388829 'gameId'
23:18:51   4371289965
23:21:39   4575238176
23:24:27   4174682307
23:27:13   3929315699
23:30:00   4457273890
23:32:48   3807681264
23:35:36   3878984600
23:38:10   4377582652 'gameId'
23:38:26   4018445418
23:41:10   4616133933
23:43:53   4540636644
23:46:37   4255948421
23:49:22   4102856515
23:52:08   4496072700
23:52:11   3883180042 'gameId'
23:55:00   3657736352
23:57:43   3788808516
00:00:29   4285309455
00:03:14   3880035008
00:05:58   4377584490
00:05:59   3765740397 'gameId'
00:08:51   3584861195
00:11:38   3638863035
00:14:27   3693913451
00:17:18   3996952081
00:20:05   3625756365
00:22:56   3550259076
00:25:40   3579619377
00:28:20   4591495377 'gameId'
00:28:30   3744770270
00:31:13   4157385096
00:33:58   4354517553
00:36:43   3540822766
00:36:47   3705449215 'gameId'
00:39:32   3664030606
00:42:17   4527533119
00:42:22   3660360787 'gameId'
00:45:08   4240747745 'gameId'
00:45:13   4240747745
00:48:05   3640438173
00:50:55   3552882282
00:53:43   3545018115 'gameId'
00:53:50   3742150414
(1366, "Incorrect integer value: 'nan' for column 'perkSubStyle' at row 7")
00:56:45   4607750058
00:59:39   4606177369
01:02:36   3672420592
01:05:33   3615273377
01:08:32   4038373965
01:11:30   4510757605
01:11:56   3640439597 'gameId'
01:12:05   3640439597 'gameId'
01:14:49   3825513397
01:17:49   3662460037
01:20:47   4476679475
01:23:44   3998004708
01:26:38   4214011539
01:29:32   3680810811
01:32:26   4078745567
01:35:02   3829184594 'gameId'
01:35:22   3649353842
01:38:14   4196710716
01:41:06   3999578580
01:41:24   3930372620 'gameId'
01:44:01   3867458174
01:46:49   4395416359 'gameId'
01:46:55   4274305832
01:49:44   3663510502
01:52:34   3690249363
01:52:38   4477729964 'gameId'
01:55:28   3546070350
01:55:35   4568956275 'gameId'
01:58:18   3927227886
01:58:36   3587489333 'gameId'
02:01:11   4355047055
02:03:58   4456234822
02:06:45   3687628789
02:09:19   4001153127 'gameId'
02:09:38   4622958736
02:12:14   3614228742 'gameId'
02:12:35   4084515141
02:15:27   3930374649
02:18:02   3795108471 'gameId'
02:18:19   3880043172
02:21:09   3830235984
02:23:56   3585917938
02:24:18   4172071996 'gameId'
02:26:52   4366058652
02:29:45   3572358673
02:32:40   3853829649
02:32:45   4265395751 'gameId'
02:35:46   4485072566
02:38:42   4422158177
02:41:28   3815032797 'gameId'
02:41:44   3542927359
02:44:44   3946104978
02:47:14   4280600840 'gameId'
02:47:45   4023699800
02:50:43   3828664819
02:53:41   4243901089
02:56:10   3807693545 'gameId'
02:56:42   3594308399
02:59:36   3672427465
03:02:29   4228697180
03:05:20   4175219978
03:08:13   3736391083
03:08:19   4134849983 'gameId'
03:11:13   4078751316
03:14:05   4631351028
(1366, "Incorrect integer value: 'nan' for column 'perkSubStyle' at row 8")
03:16:55   3928805283
(1366, "Incorrect integer value: 'nan' for column 'perkSubStyle' at row 10")
03:19:45   4037333087
03:22:40   4255437102
03:25:29   4127510974 'gameId'
03:25:38   3623145925
03:28:29   4474065511
03:31:20   3509900020
03:34:10   3888436128
03:37:00   3512521792
03:39:49   4216116486
03:42:27   4395423100 'gameId'
03:42:45   4009022875
03:45:35   4631352909
03:48:29   4357674757
03:51:19   3972847507
03:54:08   4253341745
03:56:59   4018460879
03:59:52   3628915062
04:02:47   3829193261
04:02:48   3690256943 'gameId'
04:05:44   4550613717
04:08:37   3623148420
04:11:05   3950304210 'gameId'
04:11:33   4453620765
04:14:26   3836009662
04:14:32   4604615904 'gameId'
04:17:06   3914128699 'gameId'
04:17:28   4342472044
04:20:21   4441038348
04:23:16   4032093884
04:26:12   3664043873
04:28:37   3656703911 'gameId'
04:29:14   3802980358
04:31:41   4426358880 'gameId'
04:32:19   4516536499
04:35:15   3591692627
04:38:14   3709133311
04:41:10   3765756595
04:44:10   4405912395
04:47:07   4426359806
04:50:05   3557090471
04:53:04   4017939789
04:55:29   3888965012 'gameId'
04:56:06   3762087426
04:59:04   4133283497
05:02:00   3880052582
05:04:56   3572881476
05:07:52   4494518445 'gameId'
05:07:59   3847022772
05:10:57   4518635864
05:11:15   4222937480 'gameId'
05:13:56   4511296000
05:14:08   3642026522 'gameId'
05:16:54   4220316301 'gameId'
05:17:03   3951880855
05:19:58   4319931213
05:19:58   4493994830 'gameId'
05:22:56   4541180914
05:25:51   4514442430
(1366, "Incorrect integer value: 'nan' for column 'perkSubStyle' at row 4")
05:28:45   3517771115
05:31:38   3560238632
05:34:25   3870617291 'gameId'
05:34:34   3818188500
05:37:27   4166315910
05:40:17   3705466922
05:43:10   4379177181
05:46:03   3953979782
05:48:52   4370264642
05:51:44   4018467562
05:54:35   4379177880
05:57:29   4014273616
05:59:56   3765761182 'gameId'
06:00:28   4157404399
06:03:03   3682399599 'gameId'
06:03:29   3838113191
06:06:22   3579115083
06:09:18   3531405043
06:12:14   4039964557
06:15:10   4123326503
06:18:06   4509202638
06:21:08   3733256536
06:23:27   4426889604 'gameId'
06:24:08   4260690424
06:24:23   3535600144 'gameId'
06:27:13   3802462866
06:29:52   4555864846 'gameId'
06:30:13   4210359102
06:33:10   4448910278
06:36:08   4196203625
06:39:04   4396481852
06:42:01   3711761920
06:44:59   4372364959
06:47:58   4541710192
06:50:57   3651469321
06:53:54   4334092464
06:56:26   3638886694 'gameId'
06:56:53   3699704160
06:59:46   3792503317
06:59:59   3780444741 'gameId'