In [7]:
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup
import lxml.html
import re

In [3]:
url = 'https://www.op.gg/summoner/champions/userName=hide+on+bush'

In [4]:
html = urlopen(url)
bsObject = BeautifulSoup(html, 'html.parser')
# select = soup.head.find_all('div')

# for div in select:
#     print(div.get('content'))

for div in bsObject.find_all('table'):
    print(div.get('class'))
# print(bsObject)

['ChampionStatsTable', 'sortable']

Empty DataFrame
Columns: [#, Champion, Played, KDA, Gold, CS, Max Kills, Max Deaths, Average Damage Dealt, Average Damage Taken, Double Kill, Triple Kill, Quadra Kill, Penta Kill]
Index: []

In [76]:
columns = bsObject.select('div > table > thead > tr > th')
columnlist = []

for col in columns:
    columnlist.append(col.text)
    
df = pd.DataFrame(columns=columnlist)

contents = bsObject.select('div > table > tbody > tr')

regex = re.compile(r'[\d\w.,:& ]+')

dfcontent = []

for con in contents:
    tds = con.find_all('td')
    del tds[1]
    
    for td in tds:
        text = td.text
        texts = regex.findall(text)
        dfcontent.append(texts)
            
    ser = pd.Series(dfcontent, index=columnlist)
    df = df.append(ser, ignore_index=True)
    
    dfcontent = []
    
df.drop(columns=['#'], inplace=True)
df.tail(10)

,Champion,Played,KDA,Gold,CS,Max Kills,Max Deaths,Average Damage Dealt,Average Damage Taken,Double Kill,Triple Kill,Quadra Kill,Penta Kill
70,[Swain],"[1L, 0]","[8.0 , 5.0 , 7.0, 3:1]","[14,101]","[213.0 , 5.7]",[8],[5],"[140,346]","[36,175]",[2],[],[],[]
71,[Dr. Mundo],"[1L, 0]","[1.0 , 3.0 , 2.0, 1:1]","[9,216]","[184.0 , 6.8]",[1],[3],"[171,649]","[33,312]",[],[],[],[]
72,[Blitzcrank],"[1L, 0]","[3.0 , 5.0 , 8.0, 2.2:1]","[8,585]","[41.0 , 1.1]",[3],[5],"[24,837]","[23,456]",[],[],[],[]
73,[Karma],"[1L, 0]","[3.0 , 5.0 , 9.0, 2.4:1]","[9,592]","[180.0 , 6.7]",[3],[5],"[103,589]","[13,310]",[],[],[],[]
74,[Malphite],"[1L, 0]","[4.0 , 4.0 , 3.0, 1.75:1]","[8,856]","[158.0 , 7.2]",[4],[4],"[86,175]","[12,730]",[],[],[],[]
75,[Elise],"[1L, 0]","[5.0 , 3.0 , 9.0, 4.67:1]","[11,113]","[170.0 , 6.5]",[5],[3],"[168,025]","[18,174]",[],[],[],[]
76,[Gnar],"[1L, 0]","[3.0 , 6.0 , 1.0, 0.67:1]","[7,457]","[161.0 , 8.0]",[3],[6],"[79,986]","[15,696]",[],[],[],[]
77,[Jarvan IV],"[1L, 0]","[4.0 , 7.0 , 10.0, 2:1]","[11,942]","[185.0 , 5.4]",[4],[7],"[162,525]","[38,088]",[],[],[],[]
78,[Rengar],"[1L, 0]","[6.0 , 7.0 , 5.0, 1.57:1]","[10,371]","[148.0 , 4.9]",[6],[7],"[145,469]","[33,631]",[1],[],[],[]
79,[Olaf],"[1L, 0]","[8.0 , 5.0 , 5.0, 2.6:1]","[11,929]","[167.0 , 6.2]",[8],[5],"[168,421]","[29,587]",[2],[],[],[]

In [68]:
columnlist = ['#', 'Champion', 'Win', 'Loss', 'Win Rate', 'K', 'D', 'A', 'KDA', 'Gold', 'CS', 'CS/min', 
               'Max Kills', 'Max Deaths', 'Average Damage Dealt', 'Average Damage Taken',
              'Double Kill', 'Triple Kill', 'Quadra Kill', 'Penta Kill']
df = pd.DataFrame(columns=columnlist)
df.head()

contents = bsObject.select('div > table > tbody > tr')

dfcontent = []
alldfcontents = []

# regex = re.compile(r'[\d\w.,:& ]+')

for con in contents:
    tds = con.find_all('td')
    del tds[1]
    
    for td in tds:
        text = td.text
#         texts = regex.findall(text)
        dfcontent.append(text)
#         dfcontent = dfcontent + texts
    
    if len(dfcontent) != len(columnlist):
        for i in range(len(columnlist)-len(dfcontent)):
            dfcontent.append(0)
            
    ser = pd.Series(dfcontent, index=columnlist)
    df = df.append(ser, ignore_index=True)
    
    dfcontent = []
    
# df = pd.DataFrame()
# df = df.append(alldfcontents)
df['Win'] = df['Win'].apply(lambda x: x[:-1])
df['Loss'] = df['Loss'].apply(lambda x: x[:-1])

df.drop(columns=['#'], inplace=True)
df.tail(10)

,Champion,Win,Loss,Win Rate,K,D,A,KDA,Gold,CS,CS/min,Max Kills,Max Deaths,Average Damage Dealt,Average Damage Taken,Double Kill,Triple Kill,Quadra Kill,Penta Kill
70,\nSwain\n,\n\n\n\n1L\n\n0%\n,\n\n8.0 /\n\t\t\t\t\t\t5.0 /\n\t\t\t\t\t\t7.0\...,"\n\t\t\t\t\t14,101\n\t\t\t\t",\n\t\t\t\t\t213.0 (5.7)\n\t\t\t\t,\n\t\t\t\t\t\t8\n\t\t\t\t\t,\n\t\t\t\t\t\t5\n\t\t\t\t\t,"\n\t\t\t\t\t\t140,346\n\t\t\t\t\t","\n\t\t\t\t\t\t36,175\n\t\t\t\t\t",\n\t\t\t\t\t\t\t\t\t\t\t\t\t2\n\t\t\t\t\t\t\t\...,\n,\n,\n,0,0,0,0,0,0
71,\nDr. Mundo\n,\n\n\n\n1L\n\n0%\n,\n\n1.0 /\n\t\t\t\t\t\t3.0 /\n\t\t\t\t\t\t2.0\...,"\n\t\t\t\t\t9,216\n\t\t\t\t",\n\t\t\t\t\t184.0 (6.8)\n\t\t\t\t,\n\t\t\t\t\t\t1\n\t\t\t\t\t,\n\t\t\t\t\t\t3\n\t\t\t\t\t,"\n\t\t\t\t\t\t171,649\n\t\t\t\t\t","\n\t\t\t\t\t\t33,312\n\t\t\t\t\t",\n,\n,\n,\n,0,0,0,0,0,0
72,\nBlitzcrank\n,\n\n\n\n1L\n\n0%\n,\n\n3.0 /\n\t\t\t\t\t\t5.0 /\n\t\t\t\t\t\t8.0\...,"\n\t\t\t\t\t8,585\n\t\t\t\t",\n\t\t\t\t\t41.0 (1.1)\n\t\t\t\t,\n\t\t\t\t\t\t3\n\t\t\t\t\t,\n\t\t\t\t\t\t5\n\t\t\t\t\t,"\n\t\t\t\t\t\t24,837\n\t\t\t\t\t","\n\t\t\t\t\t\t23,456\n\t\t\t\t\t",\n,\n,\n,\n,0,0,0,0,0,0
73,\nKarma\n,\n\n\n\n1L\n\n0%\n,\n\n3.0 /\n\t\t\t\t\t\t5.0 /\n\t\t\t\t\t\t9.0\...,"\n\t\t\t\t\t9,592\n\t\t\t\t",\n\t\t\t\t\t180.0 (6.7)\n\t\t\t\t,\n\t\t\t\t\t\t3\n\t\t\t\t\t,\n\t\t\t\t\t\t5\n\t\t\t\t\t,"\n\t\t\t\t\t\t103,589\n\t\t\t\t\t","\n\t\t\t\t\t\t13,310\n\t\t\t\t\t",\n,\n,\n,\n,0,0,0,0,0,0
74,\nMalphite\n,\n\n\n\n1L\n\n0%\n,\n\n4.0 /\n\t\t\t\t\t\t4.0 /\n\t\t\t\t\t\t3.0\...,"\n\t\t\t\t\t8,856\n\t\t\t\t",\n\t\t\t\t\t158.0 (7.2)\n\t\t\t\t,\n\t\t\t\t\t\t4\n\t\t\t\t\t,\n\t\t\t\t\t\t4\n\t\t\t\t\t,"\n\t\t\t\t\t\t86,175\n\t\t\t\t\t","\n\t\t\t\t\t\t12,730\n\t\t\t\t\t",\n,\n,\n,\n,0,0,0,0,0,0
75,\nElise\n,\n\n\n\n1L\n\n0%\n,\n\n5.0 /\n\t\t\t\t\t\t3.0 /\n\t\t\t\t\t\t9.0\...,"\n\t\t\t\t\t11,113\n\t\t\t\t",\n\t\t\t\t\t170.0 (6.5)\n\t\t\t\t,\n\t\t\t\t\t\t5\n\t\t\t\t\t,\n\t\t\t\t\t\t3\n\t\t\t\t\t,"\n\t\t\t\t\t\t168,025\n\t\t\t\t\t","\n\t\t\t\t\t\t18,174\n\t\t\t\t\t",\n,\n,\n,\n,0,0,0,0,0,0
76,\nGnar\n,\n\n\n\n1L\n\n0%\n,\n\n3.0 /\n\t\t\t\t\t\t6.0 /\n\t\t\t\t\t\t1.0\...,"\n\t\t\t\t\t7,457\n\t\t\t\t",\n\t\t\t\t\t161.0 (8.0)\n\t\t\t\t,\n\t\t\t\t\t\t3\n\t\t\t\t\t,\n\t\t\t\t\t\t6\n\t\t\t\t\t,"\n\t\t\t\t\t\t79,986\n\t\t\t\t\t","\n\t\t\t\t\t\t15,696\n\t\t\t\t\t",\n,\n,\n,\n,0,0,0,0,0,0
77,\nJarvan IV\n,\n\n\n\n1L\n\n0%\n,\n\n4.0 /\n\t\t\t\t\t\t7.0 /\n\t\t\t\t\t\t10.0...,"\n\t\t\t\t\t11,942\n\t\t\t\t",\n\t\t\t\t\t185.0 (5.4)\n\t\t\t\t,\n\t\t\t\t\t\t4\n\t\t\t\t\t,\n\t\t\t\t\t\t7\n\t\t\t\t\t,"\n\t\t\t\t\t\t162,525\n\t\t\t\t\t","\n\t\t\t\t\t\t38,088\n\t\t\t\t\t",\n,\n,\n,\n,0,0,0,0,0,0
78,\nRengar\n,\n\n\n\n1L\n\n0%\n,\n\n6.0 /\n\t\t\t\t\t\t7.0 /\n\t\t\t\t\t\t5.0\...,"\n\t\t\t\t\t10,371\n\t\t\t\t",\n\t\t\t\t\t148.0 (4.9)\n\t\t\t\t,\n\t\t\t\t\t\t6\n\t\t\t\t\t,\n\t\t\t\t\t\t7\n\t\t\t\t\t,"\n\t\t\t\t\t\t145,469\n\t\t\t\t\t","\n\t\t\t\t\t\t33,631\n\t\t\t\t\t",\n\t\t\t\t\t\t\t\t\t\t\t\t\t1\n\t\t\t\t\t\t\t\...,\n,\n,\n,0,0,0,0,0,0
79,\nOlaf\n,\n\n\n\n1L\n\n0%\n,\n\n8.0 /\n\t\t\t\t\t\t5.0 /\n\t\t\t\t\t\t5.0\...,"\n\t\t\t\t\t11,929\n\t\t\t\t",\n\t\t\t\t\t167.0 (6.2)\n\t\t\t\t,\n\t\t\t\t\t\t8\n\t\t\t\t\t,\n\t\t\t\t\t\t5\n\t\t\t\t\t,"\n\t\t\t\t\t\t168,421\n\t\t\t\t\t","\n\t\t\t\t\t\t29,587\n\t\t\t\t\t",\n\t\t\t\t\t\t\t\t\t\t\t\t\t2\n\t\t\t\t\t\t\t\...,\n,\n,\n,0,0,0,0,0,0

In [45]:
len(dfcontent)

21

['9',
 'Nunu',
 'Willump',
 '13W',
 '9L',
 '59%',
 '6.6',
 '5.4',
 '10.0',
 '3.09:1',
 '10,383',
 '157.4',
 '6.3',
 '14',
 '9',
 '105,356',
 '25,108',
 '9',
 '4',
 '1',
 '1']

In [55]:
text = df['CS'][0]
regex = re.compile(r'[\d\w%.,:&]+')
mc = regex.findall(text)
mc

['13']

In [57]:
df.tail()

,#,Champion,Played,KDA,Gold,CS,Max Kills,Max Deaths,Average Damage Dealt,Average Damage Taken,Double Kill,Triple Kill,Quadra Kill,Penta Kill
75,76,\nGnar\n,\n\n\n\n1L\n\n0%\n\n,\n\n3.0 /\n\t\t\t\t\t\t6.0 /\n\t\t\t\t\t\t1.0\...,"\n\t\t\t\t\t7,457\n\t\t\t\t",\n\t\t\t\t\t161.0 (8.0)\n\t\t\t\t,\n\t\t\t\t\t\t3\n\t\t\t\t\t,\n\t\t\t\t\t\t6\n\t\t\t\t\t,"\n\t\t\t\t\t\t79,986\n\t\t\t\t\t","\n\t\t\t\t\t\t15,696\n\t\t\t\t\t",\n,\n,\n,\n
76,77,\nBlitzcrank\n,\n\n\n\n1L\n\n0%\n\n,\n\n3.0 /\n\t\t\t\t\t\t5.0 /\n\t\t\t\t\t\t8.0\...,"\n\t\t\t\t\t8,585\n\t\t\t\t",\n\t\t\t\t\t41.0 (1.1)\n\t\t\t\t,\n\t\t\t\t\t\t3\n\t\t\t\t\t,\n\t\t\t\t\t\t5\n\t\t\t\t\t,"\n\t\t\t\t\t\t24,837\n\t\t\t\t\t","\n\t\t\t\t\t\t23,456\n\t\t\t\t\t",\n,\n,\n,\n
77,78,\nElise\n,\n\n\n\n1L\n\n0%\n\n,\n\n5.0 /\n\t\t\t\t\t\t3.0 /\n\t\t\t\t\t\t9.0\...,"\n\t\t\t\t\t11,113\n\t\t\t\t",\n\t\t\t\t\t170.0 (6.5)\n\t\t\t\t,\n\t\t\t\t\t\t5\n\t\t\t\t\t,\n\t\t\t\t\t\t3\n\t\t\t\t\t,"\n\t\t\t\t\t\t168,025\n\t\t\t\t\t","\n\t\t\t\t\t\t18,174\n\t\t\t\t\t",\n,\n,\n,\n
78,79,\nRengar\n,\n\n\n\n1L\n\n0%\n\n,\n\n6.0 /\n\t\t\t\t\t\t7.0 /\n\t\t\t\t\t\t5.0\...,"\n\t\t\t\t\t10,371\n\t\t\t\t",\n\t\t\t\t\t148.0 (4.9)\n\t\t\t\t,\n\t\t\t\t\t\t6\n\t\t\t\t\t,\n\t\t\t\t\t\t7\n\t\t\t\t\t,"\n\t\t\t\t\t\t145,469\n\t\t\t\t\t","\n\t\t\t\t\t\t33,631\n\t\t\t\t\t",\n\t\t\t\t\t\t\t\t\t\t\t\t\t1\n\t\t\t\t\t\t\t\...,\n,\n,\n
79,80,\nOlaf\n,\n\n\n\n1L\n\n0%\n\n,\n\n8.0 /\n\t\t\t\t\t\t5.0 /\n\t\t\t\t\t\t5.0\...,"\n\t\t\t\t\t11,929\n\t\t\t\t",\n\t\t\t\t\t167.0 (6.2)\n\t\t\t\t,\n\t\t\t\t\t\t8\n\t\t\t\t\t,\n\t\t\t\t\t\t5\n\t\t\t\t\t,"\n\t\t\t\t\t\t168,421\n\t\t\t\t\t","\n\t\t\t\t\t\t29,587\n\t\t\t\t\t",\n\t\t\t\t\t\t\t\t\t\t\t\t\t2\n\t\t\t\t\t\t\t\...,\n,\n,\n